apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: axon-landing
    namespace: axon
    annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/ssl-redirect: 'true'
spec:
    ingressClassName: nginx
    tls:
        - hosts:
              - useaxon.dev
          secretName: axon-landing-tls
    rules:
        - host: useaxon.dev
          http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: axon-landing
                            port:
                                number: 80
